//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Team4API
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Product_map
    {
        public long inventory_number { get; set; }
        public string serial_number { get; set; }
        public int number_act { get; set; }
        public string specifications { get; set; }
        public int ID_responsible_persons { get; set; }
        public int ID_status { get; set; }

        [JsonIgnore]
        public virtual Act Act { get; set; }
        [JsonIgnore]
        public virtual Responsible_persons Responsible_persons { get; set; }
        [JsonIgnore]
        public virtual Status Status { get; set; }
    }
}
