//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Team4API
{
    using System;
    using System.Collections.Generic;
    
    public partial class Story
    {
        public int StoryID { get; set; }
        public Nullable<long> inventory_number { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<System.DateTime> ChangedDate { get; set; }
        public Nullable<int> number_act { get; set; }
    
        public virtual Act Act { get; set; }
        public virtual Status Status { get; set; }
    }
}
